### ISSUE TITLE
Cheese image scaling issue is back

### ISSUE THREAD

**Issue by TheMasterOfMadness** [MHCommunity/mousehunt-improved#145]
![image](https://github.com/MHCommunity/mousehunt-improved/assets/39934989/1e66c51a-e0ef-4231-a169-d895b46ace6c)

Cheese image getting repeated, not scaled properly.

**Comment by bradp** [comment]
:notlikeduck:

**Comment by TheMasterOfMadness** [comment]
![image](https://github.com/MHCommunity/mousehunt-improved/assets/39934989/243a774c-8f88-494a-b938-ed60de5add2c)
It's back in trap setup as well as crafting section.
![image](https://github.com/MHCommunity/mousehunt-improved/assets/39934989/90fd735f-ade5-4414-9350-6bfb70f61f8c)
