### ISSUE TITLE
Info appearing outside window

### ISSUE THREAD

**Issue by jarrodknox** [MHCommunity/mousehunt-improved#152]
Inventory, traps, weapons

Click on a weapon and it shows the description, however the power icons go outside the window

![image](https://github.com/MHCommunity/mousehunt-improved/assets/88068508/6482b451-bcb7-4274-862d-6606297b9681)

**Comment by Pinaka-Pani-18** [comment]
Can I work on this issue ?

**Comment by bradp** [comment]
What version are you running @jarrodknox ? And what modules do you have enabled/disabled?

This is what it currently looks like for me:
<img width="703" alt="Screen Shot 2023-10-07 at 12 56 44 PM" src="https://github.com/MHCommunity/mousehunt-improved/assets/66798/440cfdd5-3aab-4221-87cb-f09c0f8fbd40">


@Pinaka-Pani-18 If it's still an issue in the current version, absolutely! I always welcome contributions!

**Comment by jarrodknox** [comment]
Hi, I am running 0.18.2 now and the issue has been resolved. Before it was 0.17.1 when having this issue. All good now, thanks
