### ISSUE TITLE
Send gifts window

### ISSUE THREAD

**Issue by jarrodknox** [MHCommunity/mousehunt-improved#153]
When Clicking on Friends, send gifts, the window appears for a little while and then disappears

Going into it again works fine and you can click on the send free gifts section and send gifts

After sending gifts you click OK and the windows disappears again.

So to claim gifts you have to go back into the friends, send gifts menu again

I have a number of regular people I send to and they return at different hours, along with a bunch of randoms that also send, so I always send to favourite list and any left over get dished out to the randoms.

So using the accept all / send all under the gifts menu does not really work. I also am a day behind in claiming the current gift regularly, so there are always gifts there.

Maybe having a button or option that sends to all favourite hunters first and then claims / returns all remaining gifts?

**Comment by bradp** [comment]
Added an option for this - 'Close popup after sending' in the Gift Buttons.

I added this 'Pick Random Friends' button recently, I could totally do something similar to choose all your favorites!

<img width="378" alt="Screen Shot 2023-10-07 at 9 40 26 PM" src="https://github.com/MHCommunity/mousehunt-improved/assets/66798/ee88d219-b207-4011-b3cd-6db9ae6eb55f">
