### ISSUE TITLE
Send gifts to all frequent gifters

### ISSUE THREAD

**Issue by jarrodknox** [MHCommunity/mousehunt-improved#166]
When in the send gifts interface, you have button to send to random friends, but it would be great if there could be button that selects all favorited friends

**Comment by jarrodknox** [comment]
Just updated latest version and its there, I thought I should log it as we spoke about this.

So, thanks!

But, clicking the button has locked my browser, and after reloading page it also locks browser.

Have waited a few minutes but it does not seem to come back

**Comment by jarrodknox** [comment]
Checked and it does same lockup for other gifts too.

Click Friends, send gifts, send free gifts, click on gift to send, then click select frequent gifters

**Comment by bradp** [comment]
Just fixed this in the latest release!

**Comment by jarrodknox** [comment]
Clicking the button only selects 8 out of 19 frequent gifters?

and the gifters change after each refresh it seems

<img width="444" alt="image" src="https://github.com/MHCommunity/mousehunt-improved/assets/88068508/54e52340-f9f8-41ad-bb13-d2a0ec21617f">

**Comment by jarrodknox** [comment]
Lazy to type again, but here is notes from discord

<img width="502" alt="image" src="https://github.com/MHCommunity/mousehunt-improved/assets/88068508/26bb9e9e-a6e6-4654-b168-7cb8541cf5d2">
