### ISSUE TITLE
location catch stats not up to date

### ISSUE THREAD

**Issue by JK0987** [MHCommunity/mousehunt-improved#167]
When clicking Mice, Location catch stats, the window that appears is old data

<img width="205" alt="image" src="https://github.com/MHCommunity/mousehunt-improved/assets/88068508/7bcc34b7-4690-4c7d-89f8-284e031f2fcf">

When it should be this

<img width="243" alt="image" src="https://github.com/MHCommunity/mousehunt-improved/assets/88068508/18b0aedf-68ad-45fd-a754-4ece1b20c1ad">

**Comment by bradp** [comment]
It's actually correct, you have some catches of Bonbon Gummy that were from before the event location changed. 👍
