### ISSUE TITLE
Friends name in gift window reduces to small outline when short name.

### ISSUE THREAD

**Issue by jarrodknox** [MHCommunity/mousehunt-improved#169]
In the gifting window, if a hunter has a short name then the outline box only takes one line for them, but their icon is two lines and therefore spills over into next hunter / title

<img width="203" alt="image" src="https://github.com/MHCommunity/mousehunt-improved/assets/88068508/a2ae9b3e-e20a-4bd1-bce3-568f60d0ef28">

**Comment by bradp** [comment]
Fixed in v0.24.0, will be releasing shortly.
