### ISSUE TITLE
Settings being lost on PC restart

### ISSUE THREAD

**Issue by iRoido** [MHCommunity/mousehunt-improved#170]
Version
0.22.2

Was using the one for tampermonkey and then the google chrome extension (not together)

Google Chrome
Version 118.0.5993.118 (Official Build) (64-bit)

Windows 10 Pro
21H2
OS build 19044.3086

**Comment by bradp** [comment]
Updated the title to be a little bit shorter 👍 

> everytime I restart my pc, i have to set up mousehunt improved cause i turn off some features and add those flags and some custom css you provided me before. is there no way to retain what i've setup like most script does?

**Comment by bradp** [comment]
Closing this as I believe it's been fixed with the recent changes. I'm also looking into using chrome settings sync in the future which will also fix it if it's still an issue.
