### ISSUE TITLE
Choosing Ingredients from the Crafting Table opens "Larry Loot Lexicon"

### ISSUE THREAD

**Issue by Shaft8364** [MHCommunity/mousehunt-improved#171]
- When Setting "Better inventory" is active, choosing ingredients on the crafting table opens the "Larry Loot Lexicon" pop-up instead of adding it to the crafting table;
- Tried turning it off: becomes OK again;
- Turned it on again: bug reproduced

**Comment by bradp** [comment]
Fixed in v0.24.0, will be releasing shortly.
