### ISSUE TITLE
Mouse Links in maps does not work in userscript

### ISSUE THREAD

**Issue by plaxorizor** [MHCommunity/mousehunt-improved#173]
Links to mhct/wiki does not show or is not implemented yet when clicking a mouse.
![issue](https://github.com/MHCommunity/mousehunt-improved/assets/52504216/ea3fb49e-14cb-462f-9ba5-ad8adeb24a10)

**Comment by bradp** [comment]
That's odd, I'm seeing it on my end, including with the AR rates and all of that.

What modules do you have enabled/disabled?

![Screen Shot 2023-11-08 at 9 29 33 PM](https://github.com/MHCommunity/mousehunt-improved/assets/66798/5420b143-0801-47e5-92b4-b2a546f8ad7a)

**Comment by plaxorizor** [comment]
I'm using this
![image](https://github.com/MHCommunity/mousehunt-improved/assets/52504216/642b4dfd-5eeb-4bd2-8837-0db890489849)

**Comment by plaxorizor** [comment]
> What modules do you have enabled/disabled?

I'm using this
![image](https://github.com/MHCommunity/mousehunt-improved/assets/52504216/8e958f80-5b3f-42ef-bd33-b4715c8d6dc9)

**Comment by bradp** [comment]
Try installing MouseHunt Improved as an extension & disabling the userscript version and the Mouse Links userscript

**Comment by plaxorizor** [comment]
yeah, the extension works.. I wonder why the userscript version does not work? :-/
