### ISSUE TITLE
open buttons not working as lablelled

### ISSUE THREAD

**Issue by jarrodknox** [MHCommunity/mousehunt-improved#182]
in the Inventory special page

The three buttons do not work as they are labelled

The "open" one, is fine it opens one

The "all", opens all but one

The "all but one", just opens one

![image](https://github.com/MHCommunity/mousehunt-improved/assets/88068508/d1409f12-3d9e-4025-8937-62754c71cb23)

<img width="587" alt="image" src="https://github.com/MHCommunity/mousehunt-improved/assets/88068508/7c80bc27-323b-45e5-bcc8-6b3029198f27">

**Comment by bradp** [comment]
Fixed in the release just published 🎉

**Comment by bradp** [comment]
Nope still an issue

**Comment by bradp** [comment]
Fixed finally
