### ISSUE TITLE
Add a "hide mhct" success messages feature

### ISSUE THREAD

**Issue by bradp** [MHCommunity/mousehunt-improved#200]
The MHCT submitted messages are sometimes a bit distracting. Add an option in element hiding that will hide the success messages but still surface any error messages.

Maybe have a setting to show them as compact instead of hiding? Could then style it to a small message in the top right or bottom right?

**Comment by Shaft8364** [comment]
Isn't the option to hide the messages already in the MHCT extension?

**Comment by bradp** [comment]
Oh yeah, you're totally right 🤦
