### ISSUE TITLE
Better Gifts causing timeouts and error pages

### ISSUE THREAD

**Issue by jarrodknox** [MHCommunity/mousehunt-improved#211]
When I click on accept and return all gifts in the main gift page. It has come up 3 days in a row now that the mouses tiny legs could not retrieve and the attached error

<img width="546" alt="image" src="https://github.com/MHCommunity/mousehunt-improved/assets/88068508/91d4b535-122b-4595-b83e-437d30e70132">

Also, when clicking on accept all, it does not accept all gifts available to be accepted and I have to click the button twice to get all gifts accepted.

**Comment by jarrodknox** [comment]
am using 24.1 as a tampermonkey script on chrome

**Comment by bradp** [comment]
I've been noticing a higher number of errors as well. 

There's a fix coming for the having to click twice to actually accept all the gifts, hopefully I can fix the errors as well.

**Comment by bradp** [comment]
Related: #185
