### ISSUE TITLE
FLRT tool not showing (Rift) 2024 Charms

### ISSUE THREAD

**Issue by Shaft8364** [MHCommunity/mousehunt-improved#232]
![image](https://github.com/MHCommunity/mousehunt-improved/assets/149807700/bd34535a-9944-49d5-9570-9ec6047c4663)

**Comment by Shaft8364** [comment]
Also not appearing in both quick send settings

**Comment by Shaft8364** [comment]
When leeching multiple maps, FLRT tool sometimes doesn't register the new map's maptain and suggests the previous map's maptain

**Comment by bradp** [comment]
Fixed in the last release.
