### ISSUE TITLE
Delay tooltips bug

### ISSUE THREAD

**Issue by JK0987** [MHCommunity/mousehunt-improved#233]
With the delay tooltips turned on, it is impossible to activate bottled wind. As the cheesecake tooltip always triggers and covers the button.

Turning off delay tooltips allowed the button use again

**Comment by plaxorizor** [comment]
I also have this problem. Not only in FI but also in many areas. Sometimes I get this problem when selecting/hovering on cheeses/charms/etc. Turning it off for now.

**Comment by bradp** [comment]
The way Delayed Tooltips works has been redone in the past couple updates - are you still seeing this issue?

**Comment by plaxorizor** [comment]
It seems fixed now. Thank you very much!
