### ISSUE TITLE
Wisdom, gone!

### ISSUE THREAD

**Issue by plaxorizor** [MHCommunity/mousehunt-improved#237]
Where's the wisdom in mouse views?
![image](https://github.com/MHCommunity/mousehunt-improved/assets/52504216/f03cc1d1-8208-43c0-b271-05bf63e8de11)

also, I would like to suggest to implement the Wisdom Stats like this
![wisdomstat1](https://github.com/MHCommunity/mousehunt-improved/assets/52504216/8df50979-002c-47be-994d-917b8abf24ca)

**Comment by bradp** [comment]
Fixed in c67f010d48fba5074968d887337f4eabaf9618a6, will be in the next update
