### ISSUE TITLE
New Feature: add button to send SB to maptain

### ISSUE THREAD

**Issue by JK0987** [MHCommunity/mousehunt-improved#240]
When joined a map, it would be great to have a button along the top maybe that allows you to send the maptain SB. 

This would save having to go into map / refreshing palaver and just send SB from the main page.

**Comment by jarrodknox** [comment]
What would be even cooler, is that it automatically copies the journal entry for sending to SB to clipboard.

When leeching, 
I message the person
they invite
I join
I close map interface and either press camp or refresh
I open map interface 
I hover over their name and send them sb
I close map interface
I press camp button
I copy the journal entry
I message then saying joined and paid and paste the journal entry

So adding the button, and copying the journal in one step would save a lot of time
