### ISSUE TITLE
Favorite setups not working

### ISSUE THREAD

**Issue by Shaft8364** [MHCommunity/mousehunt-improved#243]
Error popup when I activate the favorite setups setting and refresh page on hunter's camp page. Disappears when I deactivate the setting. 

As the popup says, I am unable to use favorite setups, or I don't see where the option is.

![image](https://github.com/MHCommunity/mousehunt-improved/assets/149807700/3bc29684-6e4c-4374-b512-5306f1c82429)

**Comment by bradp** [comment]
Fixed in v0.30.2
