### ISSUE TITLE
Setup Function Error

### ISSUE THREAD

**Issue by bobertrock** [MHCommunity/mousehunt-improved#245]
I have a big red error box constantly showing on the bottom of the screen and I don't know why or what caused it. The error message states "setup.find is not a function". I am running this through a Firefox extension.

<img width="960" alt="Screenshot 2024-01-24 152214" src="https://github.com/MHCommunity/mousehunt-improved/assets/157574359/cd25e478-1bbd-4936-b806-f20a63a242b8">

**Comment by bradp** [comment]
Fixed in v0.30.2
