### ISSUE TITLE
Queso region UI misalignment for swiss/brie/gouda

### ISSUE THREAD

**Issue by cxs209** [MHCommunity/mousehunt-improved#246]
The UI in the Queso region is broken for swiss/brie/gouda.
![Screenshot 2024-01-24 204330](https://github.com/MHCommunity/mousehunt-improved/assets/47068933/8d72235b-2451-4e15-a34d-19d4a3c20f3c)
If I arm swiss/brie/gouda, then the UI becomes misaligned.
![Screenshot 2024-01-24 203316](https://github.com/MHCommunity/mousehunt-improved/assets/47068933/d74942b3-5077-47db-a055-e7d5f813b902)
It seems to be specifically those three cheese. Other baits are fine

**Comment by bradp** [comment]
Fixed in v0.30.2

**Comment by bradp** [comment]
Oh wait, the first part might not be
