### ISSUE TITLE
Increased text on luck window

### ISSUE THREAD

**Issue by jarrodknox** [MHCommunity/mousehunt-improved#247]
The luck window when clicking on it has larger text, which means the highest PB is obscured

<img width="249" alt="image" src="https://github.com/MHCommunity/mousehunt-improved/assets/88068508/0851a8a4-8755-47d2-ba28-c829df84c812">

either needs to wrap text, or reduce that lines text, or even that windows text would be fine for me.

**Comment by bradp** [comment]
Fixed in 0f3fe35b072c, will be in the next release
