### ISSUE TITLE
HUD in bristle woods rift

### ISSUE THREAD

**Issue by jarrodknox** [MHCommunity/mousehunt-improved#249]
The hover for standard cheese has the quantities showing on next line, and spilling over bottom.

Looks normal when turning off HUD for that area

<img width="169" alt="image" src="https://github.com/MHCommunity/mousehunt-improved/assets/88068508/4ce46dbd-e135-4acd-a9f9-9610696c6af3">

**Comment by bradp** [comment]
Fixed in v0.31.0
