### ISSUE TITLE
Inventory Lock and Hide effect in Trap Selector

### ISSUE THREAD

**Issue by maxthen10** [MHCommunity/mousehunt-improved#255]
When we hide trap, base, or charm in inventory tab, can it also be hidden from trap selector on camp page?

**Comment by bradp** [comment]
It should be hidden in the trap selector. What component are you seeing that isn't?

**Comment by maxthen10** [comment]
Didn't realize it will hidden after 5 seconds or so. But anyway, once I click the sorter it'll all reappear. 

![Screenshot_20240209_222829_Firefox](https://github.com/MHCommunity/mousehunt-improved/assets/159222700/505ebefc-a479-46e8-b5a4-707692658ccb)
![Screenshot_20240209_222906_Firefox](https://github.com/MHCommunity/mousehunt-improved/assets/159222700/9bb3c0f8-b14b-42f7-b42c-77461c6822b4)

**Comment by bradp** [comment]
Sadly, the delay is unavoidable due to how the trap selector loads. 😢
