### ISSUE TITLE
List opened box/special items

### ISSUE THREAD

**Issue by plaxorizor** [MHCommunity/mousehunt-improved#299]
hello brad! I love the added feature about show loot as list.
Is it possible to also list these?
![image](https://github.com/MHCommunity/mousehunt-improved/assets/52504216/43a8ea9f-5a5b-4e46-88f4-07d6ab9ed28d)
I bucked-opened it.

**Comment by bradp** [comment]
![Screenshot 2024-03-10 at 4 16 18 AM](https://github.com/MHCommunity/mousehunt-improved/assets/66798/886d6a25-ce00-458a-91e0-2a639c68ce54)

🎉
