### ISSUE TITLE
LGS and non-LGS is not aligned

### ISSUE THREAD

**Issue by plaxorizor** [MHCommunity/mousehunt-improved#305]
![image](https://github.com/MHCommunity/mousehunt-improved/assets/52504216/e1f831e4-5bac-4a4c-9769-93f50f2fc592)
![image](https://github.com/MHCommunity/mousehunt-improved/assets/52504216/8ebf0181-cfef-44af-b432-54caaf81910e)

I think the non-LGS is correct

**Comment by bradp** [comment]
Fixed in v0.35.0
