### ISSUE TITLE
too much space

### ISSUE THREAD

**Issue by JK0987** [MHCommunity/mousehunt-improved#308]
Hi

Can each line be condensed a little more? Seems a lot of space between lines

![image](https://github.com/MHCommunity/mousehunt-improved/assets/88068508/1167a207-cad3-4cbb-aa0e-286e5b8af606)

Also, I wonder if the icons being there is putting more load on the servers? Each line is now retrieving a gif??

**Comment by bradp** [comment]
Yeah, I can definitely update the line heights for that.

As for the load on the server, your browser will cache the files so it's only grabbing it the first time you see it _anywhere_.

I'm also noticing some items don't have icons there, that's odd.

**Comment by bradp** [comment]
![image](https://github.com/MHCommunity/mousehunt-improved/assets/66798/72c58d0d-3b9c-41ca-8dcc-3d19e53b8bca)

Had another report about how long lists are a pain, might make sense to add the scrolling styles like the gift entries or maybe after a certain amount of items, do something else with it 🤔

**Comment by bradp** [comment]
Updated this in v0.35.0 and I think it's a bit nicer now. please reopen if you have any other suggestions for it!
