### ISSUE TITLE
quantity button change

### ISSUE THREAD

**Issue by JK0987** [MHCommunity/mousehunt-improved#320]
Would it be better to have +1 +10 +100 buttons in the shops?

a lot of time you are buying hundreds of cheese, salt, etc

Or if space were an issue then maybe have a plus / minus toggle button and then 1 5 10 100 as buttons in middle and max at end?

Not sure why we would use negative buttons that much anyway?

![image](https://github.com/MHCommunity/mousehunt-improved/assets/88068508/7496f663-ebfe-4777-870e-3f0edfd70a1e)

**Comment by bradp** [comment]
<img width="311" alt="Screen Shot 2024-03-24 at 2 05 53 PM" src="https://github.com/MHCommunity/mousehunt-improved/assets/66798/9bc7f0d2-4288-4eb2-83cd-c4281e1e91c7">

You're absolutely right, this is a great change.
