### ISSUE TITLE
Could MH Improved be keeping trap online / active?

### ISSUE THREAD

**Issue by spursdude** [MHCommunity/mousehunt-improved#326]
Hi all,
I tried out Mousehunt Improved on Windows with Chrome. Only settings I changed were to disable the improved journal, since I am used to how it has looked before. My Chrome profile is synced across 3 computers so it installed on other computers as well, and one of those computers stays on all the time. I noticed that two nights in a row, my trap stayed active all night and I went on hunts with friends throughout the entire night while I was asleep not interacting with my phone / computer at all. Same thing happened throughout the days even when my trap should have gone inactive. I uninstalled Mousehunt Improved across all devices and this stopped. Is there any way this extension could be keeping the trap active? I of course didn't see any feature specifically for this, but also wanted to bring it to the developers' attention because of the risk of users getting banned for being more active than humanly possible otherwise.
I don't have any other reasons why this might be happening. I have several other MH userscripts but nothing to auto-hunt or auto-refresh. I have the app on my Android phone but didn't need to make any changes to it and now that MH Improved is uninstalled, not having the issue anymore. Thanks.

**Comment by bradp** [comment]
Yeah, that is definitely **not** a feature and for sure something I want to fix. 

Could you go to Advanced Settings, click on Import/Export Settings, and paste that here?

I _think_ it may be due to the map sidebar functionality, which if so it'll be a pretty easy fix.

**Comment by bradp** [comment]
Should be fixed in the version that was just published. Please re-open this if not. Thanks!

**Comment by spursdude** [comment]
thanks, I will give it another try!
