### ISSUE TITLE
Feature request: Maptain Activity

### ISSUE THREAD

**Issue by AdelPereira** [MHCommunity/mousehunt-improved#328]
Would it be possible to show when last a Maptain was active? Or when the map was started?

When searching for a map on the community map listing there are a lot of maps where the Maptain hasn't been active for a very long time and as such will not accept any map invites, it would be great if we could ignore those maps.

Or when the map was started?

**Comment by bradp** [comment]
I've added a beta version of this in the version just published. You can enable it under Experiments in the settings.
