### ISSUE TITLE
Iceberg HUD enhancement bug

### ISSUE THREAD

**Issue by KennC5** [MHCommunity/mousehunt-improved#333]
When in Hidden Depths, the text shows the distance to Icewing, should be to Deep Mouse.

![image](https://github.com/MHCommunity/mousehunt-improved/assets/32643465/5708c43f-bb78-4c37-8a99-19a52eb22359)

**Comment by bradp** [comment]
Fixed in [v0.42.0](https://github.com/MHCommunity/mousehunt-improved/releases/tag/v0.42.0), please reopen if you encounter this after updating.
