### ISSUE TITLE
Clue and hunt numbers in Labyrinth HUD do not update after sounding the horn

### ISSUE THREAD

**Issue by KennC5** [MHCommunity/mousehunt-improved#337]
![image](https://github.com/MHCommunity/mousehunt-improved/assets/32643465/36eb1027-3705-4b1f-ba29-c6b2f1ec30bf)

**Comment by bradp** [comment]
What version are you on? What platform?

**Comment by KennC5** [comment]
MouseHunt Improvedv0.40.4
Windows 11 using Microsoft Edge


    On Sunday, April 14, 2024 at 02:03:19 PM CDT, Brad Parbs ***@***.***> wrote:  
 
 


What version are you on? What platform?

**Comment by bradp** [comment]
Same issue as #352 - closing this to track there.
