### ISSUE TITLE
display issue in BB

### ISSUE THREAD

**Issue by JK0987** [MHCommunity/mousehunt-improved#338]
Am seeing this display on the HUD

![image](https://github.com/MHCommunity/mousehunt-improved/assets/88068508/5ce99de0-e94c-4059-8e14-bc7c642e9cf3)

Says this?

Ballroom Floor1x Magic Beans, Lavish Lapis Beans, Royal Ruby Beans, Golden Harp Strings, and Golden Goose Egg

**Comment by SuperMari0s** [comment]
Yeah i noticed that as well when the room has more than one loot type.

**Comment by bradp** [comment]
😆 I had no idea that a room could have more than one loot type 
I'm way too new to this area
