### ISSUE TITLE
v0.41 - mice details staying after map closed

### ISSUE THREAD

**Issue by JK0987** [MHCommunity/mousehunt-improved#341]
Newly introduced since upgrading tool

![image](https://github.com/MHCommunity/mousehunt-improved/assets/88068508/d5fe12b4-1bf6-4af6-9148-c635e1628d4e)

You click on the mouse to get the info and location, and click location to travel.

Close the map window and the mouse window stays there until you close that too.

Will do it by even just clicking mouse and then closing map

**Comment by JK0987** [comment]
I found what is causing it, I had turned on the experimental feature for delay menus

Turning this off makes it close the window as per normal

**Comment by JK0987** [comment]
Scratch that, it happened again with the delayed menus turned off.

**Comment by bradp** [comment]
Fixed in [v0.42.0](https://github.com/MHCommunity/mousehunt-improved/releases/tag/v0.42.0), please reopen if you encounter this after updating.
