### ISSUE TITLE
Iceberg HUD Enhancements for Avg ft/hunt are incorrect

### ISSUE THREAD

**Issue by KennC5** [MHCommunity/mousehunt-improved#343]
Iceberg HUD Enhancements for Avg. ft/hunt are incorrect. The numbers used for the calculation are not obvious but a better metric would be the actual average for the current area. Also, the hover message does not update after sounding the horn.

I replaced all the images to correct my math error.

![image](https://github.com/MHCommunity/mousehunt-improved/assets/32643465/35753fb3-0c18-4ebd-bfd7-edb20f993281)
![image](https://github.com/MHCommunity/mousehunt-improved/assets/32643465/3f1dedbe-097e-45c0-bd70-d1ae78faf9a1)
![image](https://github.com/MHCommunity/mousehunt-improved/assets/32643465/df5a33f7-0367-4515-912b-de801668e82f)
![image](https://github.com/MHCommunity/mousehunt-improved/assets/32643465/f4800923-6b7a-4e0e-95cd-8904b422e88e)

(See Issue #333 for this Hidden Depths vs. Icewing issue)

**Comment by bradp** [comment]
Ended up redoing all of the calculations for this, so it _should_ be good now I hope!

Fixed in [v0.42.0](https://github.com/MHCommunity/mousehunt-improved/releases/tag/v0.42.0), please reopen if you encounter this after updating.
