### ISSUE TITLE
Refreshing the Dashboard did not return me to my starting location

### ISSUE THREAD

**Issue by jecklc** [MHCommunity/mousehunt-improved#344]
Version 0.41.0
Windows 11, Firefox browser.
![image](https://github.com/MHCommunity/mousehunt-improved/assets/167136287/dc20bf9a-6965-4a92-a106-80df482521ab)

**Comment by KennC5** [comment]
I had the same issue just now. I was in Furoma Rift but was left in Living Garden. My Ascended Cheese did not attract a mouse so no harm was done.

**Comment by bradp** [comment]
Should be fixed in the latest version, please re-open if not.
