### ISSUE TITLE
Travel from a map does not clear the mouse popup.

### ISSUE THREAD

**Issue by KennC5** [MHCommunity/mousehunt-improved#346]
When you open your map, click on a mouse, and then click on the location to travel, the mouse popup does not clear.

![image](https://github.com/MHCommunity/mousehunt-improved/assets/32643465/941a1d29-a772-4083-9f5c-a7b941a8b098)

![image](https://github.com/MHCommunity/mousehunt-improved/assets/32643465/58994895-f444-4a2e-ac1a-e765fcf158c1)

**Comment by bradp** [comment]
Fixed in [v0.42.0](https://github.com/MHCommunity/mousehunt-improved/releases/tag/v0.42.0), please reopen if you encounter this after updating.
