### ISSUE TITLE
The Microsoft Edge browser does not show the Minluck or Catch Rate values.

### ISSUE THREAD

**Issue by KennC5** [MHCommunity/mousehunt-improved#366]
I am using v0.42.1 on Windows 11

![image](https://github.com/MHCommunity/mousehunt-improved/assets/32643465/fa479322-c019-4d49-a429-fa3d1f17d6ec)

![image](https://github.com/MHCommunity/mousehunt-improved/assets/32643465/fd14f141-fec3-4bed-ab10-3b48021aeb26)

**Comment by wachto79** [comment]
Update to v0.43.1.  I'm getting min lucks and catch rates using Edge now.

![image](https://github.com/MHCommunity/mousehunt-improved/assets/169274492/ea2bc33b-cc0d-428b-96e1-c717074a1084)

**Comment by KennC5** [comment]
How do I update the extension? All I see is Delete.
    On Wednesday, May 8, 2024 at 12:30:45 PM CDT, wachto79 ***@***.***> wrote:  
 
 


Update to v0.43.1. I'm getting min lucks and catch rates using Edge now.

image.png (view on web)

**Comment by wachto79** [comment]
Click
![image](https://github.com/MHCommunity/mousehunt-improved/assets/169274492/d3a09a73-0128-44e3-9bcf-eb9f92b71e97)

Right Click
![image](https://github.com/MHCommunity/mousehunt-improved/assets/169274492/576b9f7c-a5d3-4f3a-bdd7-805b14b9b5af)

Click
![image](https://github.com/MHCommunity/mousehunt-improved/assets/169274492/8d5ca8d9-eee8-4c48-8153-110ee074d088)

Click
![image](https://github.com/MHCommunity/mousehunt-improved/assets/169274492/20c6642c-1dad-4a5e-8bf0-3dd3e346b227)

**Comment by KennC5** [comment]
My screens are completely different and no Update option but when I went back to mousehuntgame and refreshed it was at v0.43.1 and still no minluck or catch rates.
![image](https://github.com/MHCommunity/mousehunt-improved/assets/32643465/656b1a53-054d-49cc-a7d3-a1420e50ef1a)

**Comment by bradp** [comment]
There was an issue with how updates refresh the data files - the newest released version v0.43.2 has fixed this.
