### ISSUE TITLE
Mouse Stats by Group does not Export

### ISSUE THREAD

**Issue by wachto79** [MHCommunity/mousehunt-improved#368]
Updated to v0.43.3

Sorcerer's Apprentices now appears in the Mouse Stats by Group export table, but when you click "fetch mouse stats" the data doesn't update.  Eventually the operation times out and if you export the csv all it has is the column headers.  It hangs at the very beginning with Indigenous Mice.

**Comment by bradp** [comment]
Should be fixed in the latest version, please re-open if not.
