### ISSUE TITLE
Edge does not show Minluck or Catch Rate.

### ISSUE THREAD

**Issue by KennC5** [MHCommunity/mousehunt-improved#371]
MouseHunt Improved v0.43.3
Windows 11
Edge is up to date.

![image](https://github.com/MHCommunity/mousehunt-improved/assets/32643465/6551aeeb-086b-43bc-a61c-dc6bc7989d99)

![image](https://github.com/MHCommunity/mousehunt-improved/assets/32643465/df9288ec-da3e-4c60-9343-ed184c59d123)

**Comment by bradp** [comment]
Should be fixed in the latest version, please re-open if not.
