### ISSUE TITLE
Shop placeholder text + max button bug

### ISSUE THREAD

**Issue by fluctuatingphoton** [MHCommunity/mousehunt-improved#374]
Placeholder text in shop should reflect what you can currently afford, from what I understand. This doesn't seem to work for items that have a purchase limit. See first image where the limit is 1. I should be able to purchase 1, because the limit is 1 and I am able to afford 1, but the placeholder text is 0. Second image has no limit, but placeholder text is accurate.
<img width="266" alt="Screenshot 2024-05-13 at 2 35 43 PM" src="https://github.com/MHCommunity/mousehunt-improved/assets/86172063/0592a570-9adc-49b4-9a86-60a6677054ce">
<img width="261" alt="Screenshot 2024-05-13 at 2 36 20 PM" src="https://github.com/MHCommunity/mousehunt-improved/assets/86172063/b3e86cc2-97f5-45ab-af5c-eacdf5c4458b">
Clicking 'Max' for the first item also sets 0, instead of 1. Second item, 'Max' sets 3.

**Comment by bradp** [comment]
Fixed in v0.49.9
