### ISSUE TITLE
Updated to v0.44.4 and Edge still does not show Minluck and Catch Rate values (Re.: Issues 366 and 371).

### ISSUE THREAD

**Issue by KennC5** [MHCommunity/mousehunt-improved#376]
Mousehunt Improved v0.44.4
Latest Microsoft Edge browser
Windows 11
Lenovo ideapad 3 laptop

Minluck and Catch Rate values are shown as ![image](https://github.com/MHCommunity/mousehunt-improved/assets/32643465/b029de7f-76c2-4c6b-8818-1abf506ca9b8) and NaN% in the HUD. MinLuck is blank in the mouse box when I click on a mouse name.

**Comment by KennC5** [comment]
It appears this issue only occurs in School or Sorcery and Table of Contents with Thousandth Draft Derby Cheese. All other locations correctly display MinLuck and Catch Rate.

**Comment by bradp** [comment]
Should be all good now - feel free to reopen if not.

**Comment by KennC5** [comment]
Still not working so I am switching to the Opera browser. Opera appears to render everything correctly.
Here is what I see in Edge:
![image](https://github.com/MHCommunity/mousehunt-improved/assets/32643465/c993599f-c76c-4498-b380-62bd37833fab)
