### ISSUE TITLE
Inventory opening button features not working

### ISSUE THREAD

**Issue by PersonalPalimpsest** [MHCommunity/mousehunt-improved#396]
here is the error i get when loading the inventory page:

item.querySelector is not a function

src/utils/shared/open-all.js/addOpenAllButOneButton/<@moz-extension://da1a5319-fccc-4a8d-ac2c-1b51b46b26b6/main.js:11550:31
addOpenAllButOneButton@moz-extension://da1a5319-fccc-4a8d-ac2c-1b51b46b26b6/main.js:11546:18
onNavigation@moz-extension://da1a5319-fccc-4a8d-ac2c-1b51b46b26b6/main.js:7655:11
initOpenButtons@moz-extension://da1a5319-fccc-4a8d-ac2c-1b51b46b26b6/main.js:11600:21
src/index.js/loadModules/<@moz-extension://da1a5319-fccc-4a8d-ac2c-1b51b46b26b6/main.js:43089:35
fulfilled@moz-extension://da1a5319-fccc-4a8d-ac2c-1b51b46b26b6/main.js:59:26

**Comment by bradp** [comment]
Should be fixed now, please reopen if not
