### ISSUE TITLE
Incorrect DBC rates at Ronza

### ISSUE THREAD

**Issue by vincentxwang** [MHCommunity/mousehunt-improved#417]
Dragonbane Charms seem to not be included in the catch rate estimation at Ronza. I'm not sure if this is because of lack of data, or because there's only one mouse effected by the DBC (Malignus Vilestrom).

<img width="319" alt="Screenshot 2024-07-31 at 10 37 14 AM" src="https://github.com/user-attachments/assets/684c2ebe-3322-4049-8232-78152de0e7d9">

<img width="320" alt="Screenshot 2024-07-31 at 10 37 43 AM" src="https://github.com/user-attachments/assets/eb3dbe16-6f59-4de0-9016-6eada16de3c9">

**Comment by bradp** [comment]
Fixed in 0.54.3
